import type { Incident, Medication, Order, Patient, Session } from "./types";

const SHIFT_START = Date.parse("2026-08-27T06:30:00-05:00");
const minutesFromNow = (mins: number) =>
  new Date(SHIFT_START + mins * 60_000).toISOString();

export const HOSPITAL = "Kingston General Teaching Hospital";
export const WARD = "Medical 4B";

export const defaultSession: Session = {
  nurse: "Nadine Clarke",
  role: "Staff Nurse",
  hospital: HOSPITAL,
  ward: WARD,
};

export const medications: Medication[] = [
  {
    id: "morphine-4",
    barcode: "10041",
    brand: "Morphine Sulfate",
    generic: "morphine",
    strength: "4 mg/mL",
    strengthMg: 4,
    form: "ampoule",
    route: "IV",
    controlled: true,
    lookAlikeOf: "hydromorphone-4",
    notes: "Controlled drug. 1 mL ampoule.",
  },
  {
    id: "hydromorphone-4",
    barcode: "10042",
    brand: "Hydromorphone",
    generic: "hydromorphone",
    strength: "4 mg/mL",
    strengthMg: 4,
    form: "ampoule",
    route: "IV",
    controlled: true,
    lookAlikeOf: "morphine-4",
    notes: "7× more potent than morphine. Classic look-alike trap.",
  },
  {
    id: "paracetamol-1g",
    barcode: "20011",
    brand: "Paracetamol",
    generic: "paracetamol",
    strength: "1 g/100 mL",
    strengthMg: 1000,
    form: "infusion",
    route: "IV",
    controlled: false,
  },
  {
    id: "ondansetron-4",
    barcode: "20022",
    brand: "Ondansetron",
    generic: "ondansetron",
    strength: "4 mg/2 mL",
    strengthMg: 4,
    form: "ampoule",
    route: "IV",
    controlled: false,
  },
  {
    id: "amlodipine-5",
    barcode: "30015",
    brand: "Amlodipine",
    generic: "amlodipine",
    strength: "5 mg",
    strengthMg: 5,
    form: "tablet",
    route: "PO",
    controlled: false,
  },
  {
    id: "metformin-500",
    barcode: "30050",
    brand: "Metformin",
    generic: "metformin",
    strength: "500 mg",
    strengthMg: 500,
    form: "tablet",
    route: "PO",
    controlled: false,
    lookAlikeOf: "metformin-850",
  },
  {
    id: "metformin-850",
    barcode: "30085",
    brand: "Metformin",
    generic: "metformin",
    strength: "850 mg",
    strengthMg: 850,
    form: "tablet",
    route: "PO",
    controlled: false,
    lookAlikeOf: "metformin-500",
  },
  {
    id: "coamoxiclav-12",
    barcode: "40120",
    brand: "Co-amoxiclav",
    generic: "amoxicillin-clavulanate",
    strength: "1.2 g",
    strengthMg: 1200,
    form: "vial",
    route: "IV",
    controlled: false,
    notes: "Contains penicillin.",
  },
  {
    id: "amoxicillin-500",
    barcode: "40500",
    brand: "Amoxicillin",
    generic: "amoxicillin",
    strength: "500 mg",
    strengthMg: 500,
    form: "capsule",
    route: "PO",
    controlled: false,
    notes: "Penicillin class.",
  },
  {
    id: "amox-susp",
    barcode: "40750",
    brand: "Amoxicillin",
    generic: "amoxicillin",
    strength: "250 mg/5 mL",
    strengthMg: 250,
    form: "suspension",
    route: "PO",
    controlled: false,
  },
  {
    id: "azithromycin-500",
    barcode: "40800",
    brand: "Azithromycin",
    generic: "azithromycin",
    strength: "500 mg",
    strengthMg: 500,
    form: "vial",
    route: "IV",
    controlled: false,
  },
  {
    id: "fluclox-500",
    barcode: "40900",
    brand: "Flucloxacillin",
    generic: "flucloxacillin",
    strength: "500 mg",
    strengthMg: 500,
    form: "capsule",
    route: "PO",
    controlled: false,
    notes: "Penicillin class. Do not give if penicillin-allergic.",
  },
  {
    id: "kcl-20",
    barcode: "50020",
    brand: "Potassium chloride",
    generic: "potassium chloride",
    strength: "20 mmol/10 mL",
    strengthMg: 20,
    form: "ampoule",
    route: "IV",
    controlled: true,
    lookAlikeOf: "nacl-flush",
    notes: "High-alert. Never give undiluted IV push.",
  },
  {
    id: "nacl-flush",
    barcode: "50009",
    brand: "Sodium chloride 0.9%",
    generic: "sodium chloride",
    strength: "10 mL",
    strengthMg: 0,
    form: "ampoule",
    route: "IV",
    controlled: false,
    lookAlikeOf: "kcl-20",
  },
  {
    id: "oxytocin-10",
    barcode: "60010",
    brand: "Oxytocin",
    generic: "oxytocin",
    strength: "10 IU/mL",
    strengthMg: 10,
    form: "ampoule",
    route: "IV",
    controlled: false,
  },
  {
    id: "ferrous-200",
    barcode: "60020",
    brand: "Ferrous sulfate",
    generic: "ferrous sulfate",
    strength: "200 mg",
    strengthMg: 200,
    form: "tablet",
    route: "PO",
    controlled: false,
  },
  {
    id: "aspirin-75",
    barcode: "70075",
    brand: "Aspirin e/c",
    generic: "aspirin",
    strength: "75 mg",
    strengthMg: 75,
    form: "tablet",
    route: "PO",
    controlled: false,
    lookAlikeOf: "aspirin-300",
  },
  {
    id: "aspirin-300",
    barcode: "70300",
    brand: "Aspirin",
    generic: "aspirin",
    strength: "300 mg",
    strengthMg: 300,
    form: "tablet",
    route: "PO",
    controlled: false,
    lookAlikeOf: "aspirin-75",
  },
  {
    id: "atorva-40",
    barcode: "70040",
    brand: "Atorvastatin",
    generic: "atorvastatin",
    strength: "40 mg",
    strengthMg: 40,
    form: "tablet",
    route: "PO",
    controlled: false,
  },
  {
    id: "gtn-spray",
    barcode: "70400",
    brand: "GTN spray",
    generic: "glyceryl trinitrate",
    strength: "400 mcg",
    strengthMg: 0.4,
    form: "spray",
    route: "SL",
    controlled: false,
  },
  {
    id: "hydralazine-25",
    barcode: "80026",
    brand: "Hydralazine",
    generic: "hydralazine",
    strength: "25 mg",
    strengthMg: 25,
    form: "tablet",
    route: "PO",
    controlled: false,
    lookAlikeOf: "hydroxyzine-25",
  },
  {
    id: "hydroxyzine-25",
    barcode: "80025",
    brand: "Hydroxyzine",
    generic: "hydroxyzine",
    strength: "25 mg",
    strengthMg: 25,
    form: "tablet",
    route: "PO",
    controlled: false,
    lookAlikeOf: "hydralazine-25",
    notes: "Antihistamine. Sound-alike with hydralazine.",
  },
  {
    id: "insulin-nph",
    barcode: "90010",
    brand: "Humulin N",
    generic: "insulin isophane",
    strength: "100 IU/mL",
    strengthMg: 100,
    form: "insulin",
    route: "SC",
    controlled: true,
    lookAlikeOf: "insulin-r",
  },
  {
    id: "insulin-r",
    barcode: "90011",
    brand: "Humulin R",
    generic: "insulin regular",
    strength: "100 IU/mL",
    strengthMg: 100,
    form: "insulin",
    route: "SC",
    controlled: true,
    lookAlikeOf: "insulin-nph",
  },
];

export const patients: Patient[] = [
  {
    id: "p-devon",
    mrn: "48291014",
    wristband: "W48291014",
    name: "Devon Reid",
    sex: "M",
    dob: "1984-03-12",
    ward: WARD,
    bed: "4B-12",
    allergies: ["None known"],
    diagnosis: "Day 1 post laparotomy — pain and nausea",
    consultant: "Dr A. Grant",
  },
  {
    id: "p-marcia",
    mrn: "47110283",
    wristband: "W47110283",
    name: "Marcia Campbell",
    sex: "F",
    dob: "1959-11-02",
    ward: WARD,
    bed: "4B-03",
    allergies: ["Sulfa"],
    diagnosis: "Type 2 diabetes, hypertension — ward review",
    consultant: "Dr S. Persaud",
  },
  {
    id: "p-joseph",
    mrn: "39044117",
    wristband: "W39044117",
    name: "Joseph Brown",
    sex: "M",
    dob: "1945-07-19",
    ward: WARD,
    bed: "4B-07",
    allergies: ["Penicillin"],
    diagnosis: "Community-acquired pneumonia",
    consultant: "Dr A. Grant",
  },
  {
    id: "p-shanice",
    mrn: "51288340",
    wristband: "W51288340",
    name: "Shanice Williams",
    sex: "F",
    dob: "1998-01-28",
    ward: WARD,
    bed: "4B-18",
    allergies: ["None known"],
    diagnosis: "Day 0 postpartum — uterine atony watch",
    consultant: "Dr M. Barrett",
  },
  {
    id: "p-aisha",
    mrn: "60822109",
    wristband: "W60822109",
    name: "Aisha Mohammed",
    sex: "F",
    dob: "2017-05-04",
    ward: WARD,
    bed: "4B-21",
    allergies: ["None known"],
    diagnosis: "Otitis media — paediatric dose",
    consultant: "Dr L. Chin",
    weightKg: 28,
  },
  {
    id: "p-rohan",
    mrn: "35501992",
    wristband: "W35501992",
    name: "Rohan Barrett",
    sex: "M",
    dob: "1971-09-08",
    ward: WARD,
    bed: "4B-09",
    allergies: ["None known"],
    diagnosis: "NSTEMI — medical management",
    consultant: "Dr S. Persaud",
  },
  {
    id: "p-loretta",
    mrn: "22918873",
    wristband: "W22918873",
    name: "Loretta Chin",
    sex: "F",
    dob: "1953-02-14",
    ward: WARD,
    bed: "4B-05",
    allergies: ["ACE inhibitors — cough"],
    diagnosis: "Hypertensive urgency, step-down",
    consultant: "Dr A. Grant",
  },
  {
    id: "p-patrick",
    mrn: "40177625",
    wristband: "W40177625",
    name: "Patrick Lewis",
    sex: "M",
    dob: "1965-12-01",
    ward: WARD,
    bed: "4B-14",
    allergies: ["None known"],
    diagnosis: "New type 2 diabetes — insulin start",
    consultant: "Dr S. Persaud",
  },
  {
    id: "p-gloria",
    mrn: "31844002",
    wristband: "W31844002",
    name: "Gloria Thompson",
    sex: "F",
    dob: "1968-06-22",
    ward: WARD,
    bed: "4B-16",
    allergies: ["Penicillin"],
    diagnosis: "Cellulitis — prescribing error planted in the chart",
    consultant: "Dr A. Grant",
  },
];

export const seedOrders = (): Order[] => [
  {
    id: "o-devon-morphine",
    patientId: "p-devon",
    medicationId: "morphine-4",
    generic: "morphine",
    displayName: "Morphine sulfate",
    dose: "4 mg",
    doseMg: 4,
    route: "IV",
    frequency: "q4h PRN pain",
    dueAt: minutesFromNow(-18),
    status: "overdue",
    prescribedBy: "Dr A. Grant",
    indication: "Post-op pain",
  },
  {
    id: "o-devon-para",
    patientId: "p-devon",
    medicationId: "paracetamol-1g",
    generic: "paracetamol",
    displayName: "Paracetamol",
    dose: "1 g",
    doseMg: 1000,
    route: "IV",
    frequency: "q6h",
    dueAt: minutesFromNow(12),
    status: "due",
    prescribedBy: "Dr A. Grant",
  },
  {
    id: "o-devon-ond",
    patientId: "p-devon",
    medicationId: "ondansetron-4",
    generic: "ondansetron",
    displayName: "Ondansetron",
    dose: "4 mg",
    doseMg: 4,
    route: "IV",
    frequency: "q8h PRN nausea",
    dueAt: minutesFromNow(40),
    status: "due",
    prescribedBy: "Dr A. Grant",
  },
  {
    id: "o-marcia-amlo",
    patientId: "p-marcia",
    medicationId: "amlodipine-5",
    generic: "amlodipine",
    displayName: "Amlodipine",
    dose: "5 mg",
    doseMg: 5,
    route: "PO",
    frequency: "once daily",
    dueAt: minutesFromNow(-5),
    status: "due",
    prescribedBy: "Dr S. Persaud",
  },
  {
    id: "o-marcia-met",
    patientId: "p-marcia",
    medicationId: "metformin-500",
    generic: "metformin",
    displayName: "Metformin",
    dose: "500 mg",
    doseMg: 500,
    route: "PO",
    frequency: "twice daily with food",
    dueAt: minutesFromNow(-5),
    status: "due",
    prescribedBy: "Dr S. Persaud",
  },
  {
    id: "o-joseph-azith",
    patientId: "p-joseph",
    medicationId: "azithromycin-500",
    generic: "azithromycin",
    displayName: "Azithromycin",
    dose: "500 mg",
    doseMg: 500,
    route: "IV",
    frequency: "once daily",
    dueAt: minutesFromNow(-32),
    status: "overdue",
    prescribedBy: "Dr A. Grant",
    indication: "CAP — penicillin-allergic",
  },
  {
    id: "o-joseph-nacl",
    patientId: "p-joseph",
    medicationId: "nacl-flush",
    generic: "sodium chloride",
    displayName: "Sodium chloride 0.9% flush",
    dose: "10 mL",
    doseMg: 0,
    route: "IV",
    frequency: "with IV meds",
    dueAt: minutesFromNow(-32),
    status: "due",
    prescribedBy: "Dr A. Grant",
  },
  {
    id: "o-shanice-oxy",
    patientId: "p-shanice",
    medicationId: "oxytocin-10",
    generic: "oxytocin",
    displayName: "Oxytocin",
    dose: "10 IU",
    doseMg: 10,
    route: "IV",
    frequency: "infusion — sliding",
    dueAt: minutesFromNow(8),
    status: "due",
    prescribedBy: "Dr M. Barrett",
  },
  {
    id: "o-shanice-fe",
    patientId: "p-shanice",
    medicationId: "ferrous-200",
    generic: "ferrous sulfate",
    displayName: "Ferrous sulfate",
    dose: "200 mg",
    doseMg: 200,
    route: "PO",
    frequency: "once daily",
    dueAt: minutesFromNow(90),
    status: "due",
    prescribedBy: "Dr M. Barrett",
  },
  {
    id: "o-aisha-amox",
    patientId: "p-aisha",
    medicationId: "amox-susp",
    generic: "amoxicillin",
    displayName: "Amoxicillin suspension",
    dose: "7.5 mL (375 mg)",
    doseMg: 250,
    route: "PO",
    frequency: "three times daily",
    dueAt: minutesFromNow(-8),
    status: "due",
    prescribedBy: "Dr L. Chin",
    indication: "Weight-based paediatric dose, 28 kg",
  },
  {
    id: "o-rohan-asa",
    patientId: "p-rohan",
    medicationId: "aspirin-75",
    generic: "aspirin",
    displayName: "Aspirin e/c",
    dose: "75 mg",
    doseMg: 75,
    route: "PO",
    frequency: "once daily",
    dueAt: minutesFromNow(-2),
    status: "due",
    prescribedBy: "Dr S. Persaud",
  },
  {
    id: "o-rohan-statin",
    patientId: "p-rohan",
    medicationId: "atorva-40",
    generic: "atorvastatin",
    displayName: "Atorvastatin",
    dose: "40 mg",
    doseMg: 40,
    route: "PO",
    frequency: "at night",
    dueAt: minutesFromNow(180),
    status: "due",
    prescribedBy: "Dr S. Persaud",
  },
  {
    id: "o-loretta-hydral",
    patientId: "p-loretta",
    medicationId: "hydralazine-25",
    generic: "hydralazine",
    displayName: "Hydralazine",
    dose: "25 mg",
    doseMg: 25,
    route: "PO",
    frequency: "three times daily",
    dueAt: minutesFromNow(-14),
    status: "overdue",
    prescribedBy: "Dr A. Grant",
  },
  {
    id: "o-patrick-nph",
    patientId: "p-patrick",
    medicationId: "insulin-nph",
    generic: "insulin isophane",
    displayName: "Humulin N (NPH)",
    dose: "12 units",
    doseMg: 100,
    route: "SC",
    frequency: "morning",
    dueAt: minutesFromNow(-40),
    status: "overdue",
    prescribedBy: "Dr S. Persaud",
  },
  {
    id: "o-gloria-fluclox",
    patientId: "p-gloria",
    medicationId: "fluclox-500",
    generic: "flucloxacillin",
    displayName: "Flucloxacillin",
    dose: "500 mg",
    doseMg: 500,
    route: "PO",
    frequency: "four times daily",
    dueAt: minutesFromNow(-11),
    status: "overdue",
    prescribedBy: "Dr A. Grant",
    indication: "Planted prescribing error — patient is penicillin-allergic",
  },
];

export const seedIncidents: Incident[] = [];

export const trolleyForOrder = (order: Order): string[] => {
  const map: Record<string, string[]> = {
    "o-devon-morphine": ["morphine-4", "hydromorphone-4", "ondansetron-4", "nacl-flush"],
    "o-devon-para": ["paracetamol-1g", "nacl-flush", "ondansetron-4"],
    "o-devon-ond": ["ondansetron-4", "morphine-4", "nacl-flush"],
    "o-marcia-amlo": ["amlodipine-5", "hydralazine-25", "metformin-500"],
    "o-marcia-met": ["metformin-500", "metformin-850", "amlodipine-5"],
    "o-joseph-azith": ["azithromycin-500", "coamoxiclav-12", "amoxicillin-500", "nacl-flush"],
    "o-joseph-nacl": ["nacl-flush", "kcl-20", "azithromycin-500"],
    "o-shanice-oxy": ["oxytocin-10", "nacl-flush", "ondansetron-4"],
    "o-shanice-fe": ["ferrous-200", "amlodipine-5", "metformin-500"],
    "o-aisha-amox": ["amox-susp", "amoxicillin-500", "coamoxiclav-12"],
    "o-rohan-asa": ["aspirin-75", "aspirin-300", "atorva-40"],
    "o-rohan-statin": ["atorva-40", "aspirin-75", "amlodipine-5"],
    "o-loretta-hydral": ["hydralazine-25", "hydroxyzine-25", "amlodipine-5"],
    "o-patrick-nph": ["insulin-nph", "insulin-r", "nacl-flush"],
    "o-gloria-fluclox": ["fluclox-500", "azithromycin-500", "amoxicillin-500", "coamoxiclav-12"],
  };
  return map[order.id] ?? [order.medicationId];
};
