/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormularyRouteImport } from './routes/formulary'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as WardRouteImport } from './routes/ward'
import { Route as PatientIdRouteImport } from './routes/patient.$id'
import { Route as ScanPatientIdOrderIdRouteImport } from './routes/scan.$patientId.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormularyRoute = FormularyRouteImport.update({
  id: '/formulary',
  path: '/formulary',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const WardRoute = WardRouteImport.update({
  id: '/ward',
  path: '/ward',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIdRoute = PatientIdRouteImport.update({
  id: '/patient/$id',
  path: '/patient/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanPatientIdOrderIdRoute = ScanPatientIdOrderIdRouteImport.update({
  id: '/scan/$patientId/$orderId',
  path: '/scan/$patientId/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/formulary': typeof FormularyRoute
  '/incidents': typeof IncidentsRoute
  '/orders': typeof OrdersRoute
  '/ward': typeof WardRoute
  '/patient/$id': typeof PatientIdRoute
  '/scan/$patientId/$orderId': typeof ScanPatientIdOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/formulary': typeof FormularyRoute
  '/incidents': typeof IncidentsRoute
  '/orders': typeof OrdersRoute
  '/ward': typeof WardRoute
  '/patient/$id': typeof PatientIdRoute
  '/scan/$patientId/$orderId': typeof ScanPatientIdOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/formulary': typeof FormularyRoute
  '/incidents': typeof IncidentsRoute
  '/orders': typeof OrdersRoute
  '/ward': typeof WardRoute
  '/patient/$id': typeof PatientIdRoute
  '/scan/$patientId/$orderId': typeof ScanPatientIdOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/formulary'
    | '/incidents'
    | '/orders'
    | '/ward'
    | '/patient/$id'
    | '/scan/$patientId/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/formulary'
    | '/incidents'
    | '/orders'
    | '/ward'
    | '/patient/$id'
    | '/scan/$patientId/$orderId'
  id:
    | '__root__'
    | '/'
    | '/formulary'
    | '/incidents'
    | '/orders'
    | '/ward'
    | '/patient/$id'
    | '/scan/$patientId/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormularyRoute: typeof FormularyRoute
  IncidentsRoute: typeof IncidentsRoute
  OrdersRoute: typeof OrdersRoute
  WardRoute: typeof WardRoute
  PatientIdRoute: typeof PatientIdRoute
  ScanPatientIdOrderIdRoute: typeof ScanPatientIdOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulary': {
      id: '/formulary'
      path: '/formulary'
      fullPath: '/formulary'
      preLoaderRoute: typeof FormularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ward': {
      id: '/ward'
      path: '/ward'
      fullPath: '/ward'
      preLoaderRoute: typeof WardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/$id': {
      id: '/patient/$id'
      path: '/patient/$id'
      fullPath: '/patient/$id'
      preLoaderRoute: typeof PatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan/$patientId/$orderId': {
      id: '/scan/$patientId/$orderId'
      path: '/scan/$patientId/$orderId'
      fullPath: '/scan/$patientId/$orderId'
      preLoaderRoute: typeof ScanPatientIdOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormularyRoute: FormularyRoute,
  IncidentsRoute: IncidentsRoute,
  OrdersRoute: OrdersRoute,
  WardRoute: WardRoute,
  PatientIdRoute: PatientIdRoute,
  ScanPatientIdOrderIdRoute: ScanPatientIdOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
